### ISSUE TITLE
JSON error when trying to send Emoji on Python 3.4

### ISSUE THREAD

**Issue by salmiakki** [leandrotoledo/python-telegram-bot#80]
When I try to send an Emoji using the line from the docs (more or less) I get the following:

        bot.sendMessage(chat_id=MY_CHAT_ID, text=telegram.Emoji.PILE_OF_POO)
      File "C:\Python34\lib\site-packages\telegram\bot.py", line 126, in decorator
        result = func(self, *args, **kwargs)
      File "C:\Python34\lib\site-packages\telegram\bot.py", line 158, in decorator
        result = request.post(url, data)
      File "C:\Python34\lib\site-packages\telegram\utils\request.py", line 88, in post
        data = json.dumps(data)
      File "C:\Python34\lib\json\__init__.py", line 230, in dumps
        return _default_encoder.encode(obj)
      File "C:\Python34\lib\json\encoder.py", line 192, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "C:\Python34\lib\json\encoder.py", line 250, in iterencode
        return _iterencode(o, 0)
      File "C:\Python34\lib\json\encoder.py", line 173, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: b'\xf0\x9f\x92\xa9' is not JSON serializable

This issue might be related to issue #72.

**Comment by Humphreybas** [comment]
As I wrote in the referenced issue, the json serialize function works great without extra encoding it (it already does the encoding for you).
I guess the `telegram.Emoji.PILE_OF_POO` syntax does some extra encoding before the json serialize function get to it, this causes the exception,I don't know why serialize fails when the string is already encoded... 

You can solve this by just using the raw symbols:
`bot.sendMessage(chat_id=chat_id, text='💩') `
or if you don't want to have the unicode character in your code, use the character name:    
`bot.sendMessage(chat_id=chat_id, text='\N{PILE OF POO}') `
(the character name syntax is a Python feature: https://docs.python.org/3/howto/unicode.html#python-s-unicode-support)

(note for python2 users: this might only be valid for python3, since python3 strings always hold unicode while python2 strings holds ASCII)

**Comment by Humphreybas** [comment]
Forget what I wrote about the causes of this bug.
I think the problem is this, the symbols in the emoij class are defined as:
`PILE_OF_POO = b'\xF0\x9F\x92\xA9'`
json.dumps() cannot handle these byte objects.

**Comment by leandrotoledo** [comment]
Any suggestions on how we could improve this Emoji class?

**Comment by jh0ker** [comment]
I used telegram.emoji.Emoji.GRINNING_FACE_WITH_SMILING_EYES.decode('utf-8') for now, which works but is not that comfortable.

I suggest using sys.version_info.major to check which string should be set - the byte string or the decoded one.

**Comment by jh0ker** [comment]
I can do it, if you want

**Comment by leandrotoledo** [comment]
Hi @jh0ker, that would be highly appreciated. Thanks!

**Comment by jh0ker** [comment]
See https://github.com/leandrotoledo/python-telegram-bot/pull/85

**Comment by jh0ker** [comment]
Better solution: https://github.com/leandrotoledo/python-telegram-bot/pull/92

**Comment by leandrotoledo** [comment]
This has been released on v2.9, please run a `python-telegram-bot --upgrade`
